language: node_js
node_js:
  - "0.10"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - git submodule init
  - git submodule update
install:
  - npm install -g bower gulp
  - gem install sass
  - npm install
  - bower install
  - gulp webdriver_update
  - gulp build
  - cd build && python -m SimpleHTTPServer 8001 > /dev/null 2>&1 &
script:
  - ./node_modules/karma/bin/karma start  --single-run && ./node_modules/protractor/bin/protractor
